spring.application.name=incidentmanager

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:incidentmanager
spring.datasource.username=root
spring.datasource.password=root

# H2 (Development only)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.h2.console.settings.trace=true   

# Schema initialization
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379